# Dockerfile for node-app
FROM node:latest

WORKDIR /

COPY ./app .

RUN npm install

EXPOSE 3000

CMD ["bash", "-c", "npm install && npm start"]

# Buildar a imagem
# docker build -t node-server-2 -f dockerfile-node .

# Executar o container
# docker run -d --name node-container-2 -p 3000:3000 --link mysql-container-2 node-server-2

# Parar o container
# docker stop mysql-container-2