# Dockerfile for node-app
FROM node:latest

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD ["bash", "-c", "npm install && npm start"]

# Buildar a imagem
# docker build -t node-server -f dockerfile-node .

# Executar o container
# docker run -d --name node-container -p 3000:3000 --link mysql-server node-server

# Parar o container
# docker stop mysql-container