FROM mysql:latest

ENV MYSQL_ROOT_PASSWORD=admin
ENV MYSQL_DATABASE=meu_banco
ENV MYSQL_USER=admin
ENV MYSQL_PASSWORD=admin

COPY ./db/ /docker-entrypoint-initdb.d/

EXPOSE 3306

# Buildar a imagem
# docker build -t mysql-server-2 -f dockerfile-mysql .

# Executar o container
# docker run -d --name mysql-container-2 -p 3306:3306 mysql-server-2

# Parar o container
# docker stop mysql-container-2

